services:
  sharelatex:
    container_name: sharelatex
    image: ${MONTEX_IMAGE:?Define MONTEX_IMAGE}:${MONTEX_TAG:-latest}
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${MONTEX_HTTP_PORT:-80}:80"
    stop_grace_period: 60s
    environment:
      OVERLEAF_APP_NAME: ${OVERLEAF_APP_NAME:-MonTex}
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file,zotero"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      ADMIN_PRIVILEGE_AVAILABLE: "true"
      OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL:-http://localhost}
      OVERLEAF_NAV_TITLE: ${OVERLEAF_NAV_TITLE:-MonTex}
      GIT_BRIDGE_ENABLED: ${GIT_BRIDGE_ENABLED:-false}
      GIT_BRIDGE_HOST: ${GIT_BRIDGE_HOST:-git-bridge}
      NODE_ENV: production
    volumes:
      - sharelatex-data:/var/lib/overleaf

  git-bridge:
    container_name: git-bridge
    image: ${GIT_BRIDGE_IMAGE:-quay.io/sharelatex/git-bridge:latest}
    restart: always
    depends_on:
      - sharelatex
    environment:
      GIT_BRIDGE_API_BASE_URL: ${GIT_BRIDGE_API_BASE_URL:-http://sharelatex/api/v0}
      GIT_BRIDGE_OAUTH2_SERVER: ${GIT_BRIDGE_OAUTH2_SERVER:-http://sharelatex}
      GIT_BRIDGE_POSTBACK_BASE_URL: ${GIT_BRIDGE_POSTBACK_BASE_URL:-http://git-bridge:8000}
      GIT_BRIDGE_ROOT_DIR: /data/git-bridge
      LOG_LEVEL: ${GIT_BRIDGE_LOG_LEVEL:-INFO}
    volumes:
      - git-bridge-data:/data/git-bridge

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    command: "--replSet overleaf"
    volumes:
      - mongo-data:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js:ro
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    volumes:
      - redis-data:/data

volumes:
  sharelatex-data:
  git-bridge-data:
  mongo-data:
  redis-data:
